-- demo stock, generated by scripts/demo/generate.mjs
BEGIN;
INSERT INTO inventory (sku, quantity) VALUES ('ADY350-V2', 5)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('AIMA2-L', 9)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('AIMA2-M', 11)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('AIMA2-XL', 6)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('ANSMOTION+-BLK', 8)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('APPR2-USBC-WHT', 30)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('ASGC26', 10)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('ASVSB14-16512-SLV', 11)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('AW8-45-GPS-MID', 13)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('BQC45-BLK', 12)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('BZN-L', 7)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('BZN-M', 8)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('CGA2100-1A-BLK', 22)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('CNCT70-WHT', 26)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('CNR5-BODY', 3)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('CNR6M3-BODY', 4)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('CZNAUTO-STL', 9)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('FSLCHRONO-LTHR', 14)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('GA55-256-BLK', 25)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('GA55-256-LBL', 18)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('GS24U-256-TBL', 14)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('GS24U-512-TVL', 4)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('GTABS8-128-GPH', 12)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('GTABS8U-512-GPH', 3)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('GW6-40-BT-GPH', 16)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('GZF4-256-GRY', 6)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('HPSPX13-16512-NBL', 5)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('IP15-128-BLU', 20)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('IP15-128-PNK', 12)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('IP15-256-BLK', 9)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('IP15PM-256-BLU', 8)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('IP15PM-256-NAT', 15)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('IP15PM-512-NAT', 5)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('JBFLIP6-SQD', 19)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('LEV501-32-WASH', 12)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('LEV501-34-WASH', 10)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('LTPT14-16512-BLK', 15)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('MBA15-M4-16256-SLV', 10)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('MBP14-M3P-512-SPG', 7)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('NKAF1-FLAX', 17)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('NKAMDn-40', 2)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('NKD850-BODY', 2)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('PMSC21-RED', 4)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('SNA7-BODY', 6)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('TNFAP-L', 4)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('TNFAP-M', 8)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('TNFAP-S', 5)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('TNFML-L', 7)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('TNFML-M', 9)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
INSERT INTO inventory (sku, quantity) VALUES ('TNFML-S', 6)
  ON CONFLICT (sku) DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();
DELETE FROM inventory_transactions WHERE reference = 'demo-seed';
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'ADY350-V2', 'IMPORT', 5, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'AIMA2-L', 'IMPORT', 9, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'AIMA2-M', 'IMPORT', 11, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'AIMA2-XL', 'IMPORT', 6, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'ANSMOTION+-BLK', 'IMPORT', 8, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'APPR2-USBC-WHT', 'IMPORT', 30, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'ASGC26', 'IMPORT', 10, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'ASVSB14-16512-SLV', 'IMPORT', 11, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'AW8-45-GPS-MID', 'IMPORT', 13, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'BQC45-BLK', 'IMPORT', 12, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'BZN-L', 'IMPORT', 7, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'BZN-M', 'IMPORT', 8, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'CGA2100-1A-BLK', 'IMPORT', 22, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'CNCT70-WHT', 'IMPORT', 26, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'CNR5-BODY', 'IMPORT', 3, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'CNR6M3-BODY', 'IMPORT', 4, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'CZNAUTO-STL', 'IMPORT', 9, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'FSLCHRONO-LTHR', 'IMPORT', 14, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'GA55-256-BLK', 'IMPORT', 25, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'GA55-256-LBL', 'IMPORT', 18, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'GS24U-256-TBL', 'IMPORT', 14, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'GS24U-512-TVL', 'IMPORT', 4, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'GTABS8-128-GPH', 'IMPORT', 12, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'GTABS8U-512-GPH', 'IMPORT', 3, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'GW6-40-BT-GPH', 'IMPORT', 16, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'GZF4-256-GRY', 'IMPORT', 6, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'HPSPX13-16512-NBL', 'IMPORT', 5, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'IP15-128-BLU', 'IMPORT', 20, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'IP15-128-PNK', 'IMPORT', 12, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'IP15-256-BLK', 'IMPORT', 9, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'IP15PM-256-BLU', 'IMPORT', 8, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'IP15PM-256-NAT', 'IMPORT', 15, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'IP15PM-512-NAT', 'IMPORT', 5, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'JBFLIP6-SQD', 'IMPORT', 19, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'LEV501-32-WASH', 'IMPORT', 12, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'LEV501-34-WASH', 'IMPORT', 10, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'LTPT14-16512-BLK', 'IMPORT', 15, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'MBA15-M4-16256-SLV', 'IMPORT', 10, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'MBP14-M3P-512-SPG', 'IMPORT', 7, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'NKAF1-FLAX', 'IMPORT', 17, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'NKAMDn-40', 'IMPORT', 2, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'NKD850-BODY', 'IMPORT', 2, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'PMSC21-RED', 'IMPORT', 4, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'SNA7-BODY', 'IMPORT', 6, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'TNFAP-L', 'IMPORT', 4, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'TNFAP-M', 'IMPORT', 8, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'TNFAP-S', 'IMPORT', 5, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'TNFML-L', 'IMPORT', 7, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'TNFML-M', 'IMPORT', 9, 'demo-seed');
INSERT INTO inventory_transactions (id, sku, type, quantity, reference)
  VALUES (gen_random_uuid(), 'TNFML-S', 'IMPORT', 6, 'demo-seed');
COMMIT;