spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thanhlam1906/ecommerce-config.git
          default-label: main

server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized
